### ISSUE TITLE
Melhorar visualização do Markdown Widget

### ISSUE THREAD

**Issue by meccin** [avuenja/tabnews-app#10]
O Markdown Widget ainda não está legal, algumas extenso˜es carregadas, acabaram se conflitando.

* Não conseguimos clicar nos links
* Imagens e tags HTML não estão renderizando, somente markdown.

Link de referência: https://github.com/flutter/packages/tree/main/packages/flutter_markdown
Link de referência extensões: https://github.com/dart-lang/markdown

**Comment by meccin** [comment]
@arcbueno tava pensando em logo mais verificar esse cara, por que os links não tão rolando.

E acredito que seja colocar um: 

```dart
onTapLink: (text, href, title) {
  href != null ? launch(href) : null;
}
```

Utilizando o url_launcher, e podemos verificar também se o link é www.tabnews.com.br, e abrir no próprio app, ao invés de abrir no navegador.

**Comment by arcbueno** [comment]
> @arcbueno tava pensando em logo mais verificar esse cara, por que os links não tão rolando.
> 
> E acredito que seja colocar um: 
> 
> ```dart
> onTapLink: (text, href, title) {
>   href != null ? launch(href) : null;
> }
> ```
> 
> Utilizando o url_launcher, e podemos verificar também se o link é www.tabnews.com.br, e abrir no próprio app, ao invés de abrir no navegador.

Massa, tava dando uma olhada justamente nesse no tempo livre de hoje, mas não andei muito. A minha ideia é essa mesmo que tu tas fazendo. Se eu conseguir adiantar algo eu subo o PR

Sei que tem a função canLaunch do pacote que tu pode verificar antes pra ter certeza se pode

**Comment by meccin** [comment]
@arcbueno Acabei criando uma util de open link, para tratarmos conforme vai aparecendo outras questões.

Mas agora, tá bem mais fluído. E carreguei o Flavor de Github Web, para poder carregar os itens melhores do Github.

Acredito que num futuro próximo, seria mexer no image builder, para podermos colocar um zoom na imagem, para poder visualizar melhor.
