### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by Jeiel0rbit** [avuenja/tabnews-app#2]
Ainda não testei aplicativo para Android, mas seria legal se disponibilizar para outros testarem manualmente em formato de apk.

**Comment by meccin** [comment]
Boa @Jetrom17, irei verificar aqui, para disponibilizar um guia, ou o apá aqui na parte de release, para o pessoal verificar!

**Comment by leonardodimarchi** [comment]
Aproveitando a Issue de sugestão, acho que seria interessante adicionar mais duas coisinhas para trazer mais pessoas para o projeto:

- Criar uma branch de desenvolvimento para receber os pull-requests
- Guideline de contribuição (com o modelo de commit, comandos para rodar o app, etc)

Cheguei aqui a partir da própria postagem no Tabnews, muito bom!!! 😊

**Comment by meccin** [comment]
Fala @leonardodimarchi! Muito boa a sugestão!

Com certeza meu querido! Vou te dizer que quero fazer isso aí, mas não consegui parar para pensar, desde que comecei o projeto para conseguir adiantar ao máximo.

Mas acredito que será necessário sim, se não o pessoal acaba não conseguindo contribuir. 

Vou agilizar isso <3

Abração
