### ISSUE TITLE
Refinamento: Page Login

### ISSUE THREAD

**Issue by decaidenza** [avuenja/tabnews-app#33]
Oi, boar tarde!
Percebi que no dark mode, o texto de criar conta não está muito visível e as labels dos inputs estão muito próximas da margem.

**Comment by meccin** [comment]
Olá @DecaiDenza, tudo bem?

Opa, perfeito meu querido. Eu enviei uma versão nova [Alpha v0.0.5](https://github.com/avuenja/tabnews-app/releases/tag/v0.0.5), que você pode baixar, onde ajustei a questão do Dark Mode.

A questões da margem seriam laterais? Qualquer coisa, você pode subir um print, para verificarmos melhor.

Segue um print abaixo.

![IMG_820336212F55-1](https://user-images.githubusercontent.com/5226773/204155208-a48e0f61-4b28-4d86-a1cc-b0192268bde6.jpeg)

**Comment by meccin** [comment]
![CleanShot 2022-11-28 at 21 14 24](https://user-images.githubusercontent.com/5226773/204372121-569879d1-14f3-4beb-86cb-6178a9bb06f2.png)

Aumentado o espaçamento dos campos das laterais.

A próxima versão irá ajustar o que foi comentado.
