### ISSUE TITLE
Lentidão para visualizar post com muitos comentários

### ISSUE THREAD

**Issue by meccin** [avuenja/tabnews-app#6]
Ao adicionar no app a visualização de todos os comentários e seus sub-comentários.

Acabou rolando lentidão em posts com muitos comentários.

Verificar um jeito para deixar lazy, pois vem todos os comentários em um array sem paginação.

**Comment by arcbueno** [comment]
Pelo que vi rapidamente pode ser por conta do parâmetro shrinkWrap, que se tiver true ele tenta buildar todos os itens de uma vez, ai causa essa lentidão. Posso dar uma olhada mais tarde, mas creio que pode ser isso

**Comment by meccin** [comment]
Fala @arcbueno, booaa.

Bora testar isso, eu acabei colocando, por causa de estar dentro de uma Column, e não tamanho, a lista não renderizava corretamente.

Bora testar para ver se achamos a solução.

**Comment by arcbueno** [comment]
@avuenja  Opa, tu pode liberar para subir branchs de outros usuários? Fiz uma correção e iria pedir pra tu testar.
Só lembrando de tu configurar para a main não receber commit sem ser via PR

**Comment by meccin** [comment]
Oi @arcbueno, claro, deixa eu ver como libero aqui, e já dou um edit aqui.

**Comment by meccin** [comment]
@arcbueno, eu não sei como liberar isso, procurei não achei nada... :(

Vou te adicionar aqui, como colab.

**Comment by arcbueno** [comment]
@avuenja tá certo, assim que puder eu te dou um auxilio nisso e qualquer coisa eu abro uma issue pra deixar o projeto aberto

**Comment by meccin** [comment]
Obrigado @arcbueno ♥️

Eu adicionei commit lint no projeto. E aos poucos vamos melhorando questão de contribuição também.

**Comment by arcbueno** [comment]
@avuenja Dei uma ajustada e subi o PR, tu pode dar uma testada para confirmar a resolução?

**Comment by meccin** [comment]
Boa @arcbueno, com certeza, já vou testar aqui!

Bora pra cima!

**Comment by meccin** [comment]
Fix #25
